name: Cancel
on:
  push:
    branches:
      - master
      - baymerge-testing

jobs:
  cancel:
    name: 'Cancel Redundant Builds'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          workflow_id: 27212, 3545321
          access_token: ${{ github.token }}